@startuml

!include /media/win/E/chuanqing/gitspace/shell-func/define.puml


    package iterator{
    +interface Aggregate{
        +{abstract} Iterator iterator()
    }

    +interface Iterator{
        +{abstract} boolean hasNext()
        +{abstract} Object next()
    }

    +class BookShelf{
        books
            last
            getBookAt()
            appendBook()
            getLength()
            iterator()
    }

    +class BookShelfIterator{
        bookShelf
            index
            hasNext()
            next()
    }
    +class Book{
        name
            getName()
    }


}



    Aggregate -> Iterator : Creates >

        BookShelf <-o BookShelfIterator

        Aggregate <|.. BookShelf

        Iterator <|.. BookShelfIterator

        BookShelf o--> Book
@enduml
